name: Run Arxiv Papers Daily
on: 
  schedule:
    - cron:  '*/10 * * * *'
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Set up Python Env
        uses: actions/setup-python@v1
        with:
          python-version: 3.7       

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install arxiv
          pip install requests
          
      - name: Run arxiv report 
        env:
          SCKEY: ${{ secrets.SERECT }}$
        run: |
          python arxiv_daily.py "${secret}"
